<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MLCCS.VideoSearch.Installer.Acceptance</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\installer\MLCCS.VideoSearch.OnlineInstaller\MLCCS.VideoSearch.OnlineInstaller.csproj" />
  </ItemGroup>
</Project>
